apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-noti
  namespace: laravel
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=local
    APP_KEY=base64:Y3Z2NTkydjcyNW5zZ2hzdmNnM3VpNm43eHk2eTN2OWE=
    APP_DEBUG=true
    APP_URL=http://localhost:8083

    LOG_CHANNEL=stack
    LOG_DEPRECATIONS_CHANNEL=null
    LOG_LEVEL=debug

    DB_CONNECTION=mysql
    DB_HOST=mysql-noti
    DB_PORT=3306
    DB_DATABASE=noti_db
    DB_USERNAME=root
    DB_PASSWORD=root

    BROADCAST_DRIVER=log
    CACHE_DRIVER=redis
    FILESYSTEM_DISK=local
    QUEUE_CONNECTION=rabbitmq
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    QUEUE_CONNECTION=rabbitmq
    RABBITMQ_HOST=rabbitmq-noti
    RABBITMQ_PORT=5672
    RABBITMQ_USER=guest
    RABBITMQ_PASSWORD=guest
    RABBITMQ_VHOST=/
    RABBITMQ_QUEUE=notification

    MEMCACHED_HOST=127.0.0.1

    REDIS_HOST=redis-noti
    REDIS_PORT=6379
    REDIS_PASSWORD=null

    MAIL_MAILER=smtp
    MAIL_HOST=mailpit-noti
    MAIL_PORT=1025
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS="hello@example.com"
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=
    AWS_USE_PATH_STYLE_ENDPOINT=false

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_HOST=
    PUSHER_PORT=443
    PUSHER_SCHEME=https
    PUSHER_APP_CLUSTER=mt1

    VITE_APP_NAME="${APP_NAME}"
    VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    VITE_PUSHER_HOST="${PUSHER_HOST}"
    VITE_PUSHER_PORT="${PUSHER_PORT}"
    VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
    VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

    JWT_SECRET=25cf7c74ce6c200e23233578547e96fae378ec618856572264fe5dd8a468e2ed
    JWT_ALGO=HS256
