apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-noti
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-noti
  template:
    metadata:
      labels:
        app: webserver-noti
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-noti
            items:
              - key: default.conf
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-noti
  namespace: laravel
spec:
  type: NodePort
  selector:
    app: webserver-noti
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
