apiVersion: v1
kind: ConfigMap
metadata:
  name: supervisor-conf-event
  namespace: laravel
data:
  supervisor.conf: |
    [supervisord]
    nodaemon=true
    logfile=/var/log/supervisor/supervisord.log
    logfile_maxbytes=50MB
    logfile_backups=10
    loglevel=info
    pidfile=/var/run/supervisord.pid
    childlogdir=/var/log/supervisor

    [supervisorctl]
    serverurl=unix:///var/run/supervisor.sock

    [program:php-fpm]
    command=php-fpm
    autostart=true
    autorestart=true
    stdout_logfile=/var/log/supervisor/php-fpm.log
    stderr_logfile=/var/log/supervisor/php-fpm-error.log

    [program:rabbitmq-blacklisted-consumer]
    command=php /var/www/artisan rabbitmq:consume-blacklisted
    autostart=true
    autorestart=true
    stdout_logfile=/var/log/supervisor/rabbitmq-blacklisted-consumer.log
    stderr_logfile=/var/log/supervisor/rabbitmq-blacklisted-consumer-error.log
