apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-event
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-event
  template:
    metadata:
      labels:
        app: redis-event
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-event
  namespace: laravel
spec:
  selector:
    app: redis-event
  ports:
    - port: 6379
      targetPort: 6379
