apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-chat-pvc
  namespace: laravel
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-chat
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-chat
  template:
    metadata:
      labels:
        app: mysql-chat
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "chat_db"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-chat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-chat
  namespace: laravel
spec:
  selector:
    app: mysql-chat
  ports:
    - port: 3306
      targetPort: 3306
