# k8s/secret-env.yaml
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel
type: Opaque
data:
  # Base64 encode the password: echo -n "root" | base64
  DB_PASSWORD: cm9vdA==
