# k8s/configmap-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-env
  namespace: laravel
data:
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:bGZhczhndGs1M2R1MTR2ODJmcWVnZzFvM2IxYmI2dDk="
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  
  LOG_CHANNEL: "stack"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  DB_CONNECTION: "mysql"
  DB_HOST: "db"
  DB_PORT: "3306"
  DB_DATABASE: "laravel"
  DB_USERNAME: "root"

  QUEUE_CONNECTION: "rabbitmq"

  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  FILESYSTEM_DISK: "local"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  RABBITMQ_QUEUE: "blacklisted"

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_HOST: "redis"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "sandbox.smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "0375b756294e8a"
  MAIL_PASSWORD: "3a9c99f6b63599"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "no-reply@example.com"
  MAIL_FROM_NAME: "Laravel"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  PUSHER_HOST: ""
  PUSHER_PORT: "443"
  PUSHER_SCHEME: "https"
  PUSHER_APP_CLUSTER: "mt1"

  VITE_APP_NAME: "Laravel"
  VITE_PUSHER_APP_KEY: ""
  VITE_PUSHER_HOST: ""
  VITE_PUSHER_PORT: "443"
  VITE_PUSHER_SCHEME: "https"
  VITE_PUSHER_APP_CLUSTER: "mt1"

  JWT_SECRET: "25cf7c74ce6c200e23233578547e96fae378ec618856572264fe5dd8a468e2ed"
  JWT_ALGO: "HS256"
  JWT_BLACKLIST_ENABLED: "true"
