# k8s/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: laravel
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: laravel
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-app
  namespace: laravel
spec:
  type: ClusterIP
  selector:
    app: laravel-app
  ports:
    - name: app
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-nginx
  namespace: laravel
spec:
  type: NodePort # or LoadBalancer if you have a LB set up
  selector:
    app: laravel-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080 # NodePort for external access via minikube service command
