services: 
  db:
    image: mysql:5.7
    container_name: laravel-db-event
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_manager_db
    ports:
      - "3308:3306"
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: event_manager_webserver
    restart: unless-stopped
    ports:
      - '8081:80'
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
    networks:
      - app-network
      - shared

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_manager_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./Certificados:/etc/rabbitmq/certs
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network
      - shared

  redis:
    image: redis:alpine
    container_name: redis1
    restart: unless-stopped
    ports:
      - "6479:6379" # Correctly map host port 6479 to container port 6379
    networks:
      - app-network
      - shared

networks:
  app-network:
    driver: bridge
  shared:
    external: true
