services: 
  webserver:
    image: nginx:alpine
    container_name: gateway_webserver
    restart: unless-stopped
    ports:
      - '8069:80'
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - gatt
      - shared

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    env_file:
      - .env
    depends_on:
      - webserver
    networks:
      - gatt
      - shared

networks:
  gatt:
    driver: bridge
  shared:
    external: true
