services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5671:5671" # Porta para AMQPS
      - "15672:15672" # Porta para o painel de administração HTTPS
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./Certificados:/etc/rabbitmq/certs # Montar certificados
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf # Configuração personalizada
    networks:
      - shared

networks:
  shared:
    external: true
